Missing history banner do not overlap images #1846
c2corg/c2c_ui pull request #1847
Opened 2021-04-23 09:36 UTC by cbeauchesne

2021-04-23 18:27 UTC, ataraxido requested changes

2021-04-23 18:27 UTC, ataraxido commented on src/views/document/RouteView.vue
> +          <div v-else-if="showMissingHistoryBanner" class="notification is-info no-print missing-histoy-banner">
typo histoy -> history

2021-04-23 18:27 UTC, ataraxido commented on src/views/document/RouteView.vue
> +.missing-histoy-banner {
typo histoy -> history

2021-04-24 20:40 UTC, brunobesson approved these changes

2021-04-25 18:11 UTC, ataraxido approved these changes

2021-04-26 07:53 UTC, merged