chore: #3768 use openresty debian bookworm as production base docker image
c2corg/c2c_ui pull request #3770
Opened 2023-12-23 00:54 UTC by florentcadot

Hi! Here is a PR to use the last debian version (bookworm) for the openresty base docker image as suggested in this issue https://github.com/c2corg/c2c_ui/issues/3768.

Here is a solution for variable substitution using **sed**  instead of  **envsubst** as it was not provided with this debian version.

2023-12-23 09:48 UTC, LaurentBonnaud commented
Thanks for this update!
How about installing the `gettext-base` package on top of the image to get the `envsubst` command back?

2023-12-23 10:23 UTC, florentcadot commented
> Thanks for this update! How about installing the `gettext-base` package on top of the image to get the `envsubst` command back?

(Thanks for the fast review :smile:) 

You're right, the image is correctly built using `gettext-base` package, just need to add the following line in the Dockerfile :

`RUN apt-get update && apt-get install -y gettext-base
`

But as we can achieve exactly the same result using the `sed` command available without installing anything else it seems "lighter" to me.

I think it is just a question of coding style/approach, no problem for me if there is a consensus about using the `gettext-base` package

2023-12-23 11:46 UTC, LaurentBonnaud commented
> But as we can achieve exactly the same result using the sed command available without installing anything else it seems "lighter" to me.

Indeed, lighter, but more difficult to read.

2023-12-30 17:35 UTC, florentcadot commented
> > But as we can achieve exactly the same result using the sed command available without installing anything else it seems "lighter" to me.
> 
> Indeed, lighter, but more difficult to read.

Updated installing the `gettext-base` package on top of the image

2023-12-31 13:51 UTC, LaurentBonnaud commented
Thanks for this new version!

2024-01-04 11:58 UTC, brunobesson requested changes
All good, except some cache optimizations

2024-01-04 11:58 UTC, brunobesson commented on Dockerfile
> +
for cache reasons, it is best to run this command as soon as possible, i.e. before line 14.

2024-01-04 11:58 UTC, brunobesson requested changes
All good, except some cache optimizations

2024-01-04 12:02 UTC, brunobesson commented
I do think, based on our needs, we could use alpine tag instead. When I first built the image, there weren't so many options.
Using the alpine tag would also simplify the update process.

2024-01-04 15:30 UTC, florentcadot commented
> I do think, based on our needs, we could use alpine tag instead. When I first built the image, there weren't so many options. Using the alpine tag would also simplify the update process.

I agree using the alpine tag would simplify the update process in the future.
I don't get why alpine would be better for the project need. Could you explain, please ?

2024-01-04 15:58 UTC, brunobesson commented
> I don't get why alpine would be better for the project need. Could you explain, please ?

I don't say it is better, it is however lighter, and the constraints that come with it do not apply to our usecase.

2024-01-04 16:22 UTC, florentcadot commented
> > I don't get why alpine would be better for the project need. Could you explain, please ?
> 
> I don't say it is better, it is however lighter, and the constraints that come with it do not apply to our usecase.

For the "lighter" part, not sure if you're talking about the openresty image, if yes:

openresty/openresty:alpine 42.08 MB
https://hub.docker.com/r/openresty/openresty/tags?page=1&name=alpine

openresty/openresty:bookworm   35.01 MB
https://hub.docker.com/r/openresty/openresty/tags?page=1&name=bookworm

So bookworm seems lighter, or maybe I missed something ? 
 
Anyway, thank you for taking time to reply and your review :smile: 

And let me know if you need a PR using alpine

2024-01-04 17:35 UTC, brunobesson commented
Alpine-apk is 9mb.
I haven't checked th base images for this. Anyway, bookworm is fine, but
we'll need to stay aware of debian updates.

Le jeu. 4 janv. 2024, 17:22, Florent Cadot ***@***.***> a
écrit :

> I don't get why alpine would be better for the project need. Could you
> explain, please ?
>
> I don't say it is better, it is however lighter, and the constraints that
> come with it do not apply to our usecase.
>
> For the "lighter" part, not sure if you're talking about the openresty
> image, if yes:
>
> openresty/openresty:alpine 42.08 MB
> https://hub.docker.com/r/openresty/openresty/tags?page=1&name=alpine
>
> openresty/openresty:bookworm 35.01 MB
> https://hub.docker.com/r/openresty/openresty/tags?page=1&name=bookworm
>
> So bookworm seems lighter, or maybe I missed something ?
>
> Anyway, thank you for taking time to reply and your review 😄
>
> And let me know if you need a PR using alpine
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/c2corg/c2c_ui/pull/3770#issuecomment-1877384694>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARBNKEBP23BRKDH6QGQX43YM3JLHAVCNFSM6AAAAABBANEVZ6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNZXGM4DINRZGQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-01-10 15:59 UTC, brunobesson approved these changes

2024-01-10 15:59 UTC, merged